"""Catalog FQNs, lakehouse IDs, and business constants for HC / Okta / Cursor pipelines.

Injected into notebooks by ``bootstrap.init_notebook`` (names in ``CONFIG_NAMES``).
"""

from __future__ import annotations

import os

WORKSPACEID = os.environ.get("FABRIC_WORKSPACE_ID", "4cecee03-0629-4081-8ae8-b749ee04d43f")
LAKEHOUSE_AI_MEDALLION_ID = os.environ.get(
    "LAKEHOUSE_AI_MEDALLION_ID", "1ee46463-2495-44f5-9dc9-d635d0067483"
)
LAKEHOUSE_AI_MEDALLION_BRONZE_ID = os.environ.get(
    "LAKEHOUSE_AI_MEDALLION_BRONZE_ID", "36e5350a-61f6-4120-8c32-a38f55722907"
)
LAKEHOUSE_AI_MEDALLION_SILVER_ID = os.environ.get(
    "LAKEHOUSE_AI_MEDALLION_SILVER_ID", LAKEHOUSE_AI_MEDALLION_ID
)
# AI_Medallion_Silver.dbo (CoreCountry_Excel_Hours_Historic) — separate Fabric lakehouse.
LAKEHOUSE_AI_MEDALLION_SILVER_DB_ID = os.environ.get(
    "LAKEHOUSE_AI_MEDALLION_SILVER_DB_ID", "a1be6c30-3d8c-49ed-ace8-48930a92ba14"
)

BRONZE_DATABASE = "AI_Medallion_Bronze"
SILVER_DATABASE = "AI_Medallion"
GOLD_DATABASE = "AI_Medallion"
SILVER_SCHEMA = "Silver"
GOLD_SCHEMA = "Gold"
BRONZE_MEDALLION_DATABASE = "AI_Medallion"
BRONZE_CURSOR_SCHEMA = "Bronze"
COUNTRY_DATABASE = "AI_Medallion_Silver"
COUNTRY_TABLE = "CoreCountry_Excel_Hours_Historic"

TABLE_HC_BRONZE = f"{BRONZE_DATABASE}.dbo.HC_Bronze_Historical"
TABLE_OKTA_BRONZE = f"{BRONZE_DATABASE}.dbo.CoreOktaUser"
TABLE_CURSOR_BRONZE = f"{BRONZE_MEDALLION_DATABASE}.{BRONZE_CURSOR_SCHEMA}.cursor_usage"
TABLE_COUNTRY = f"{COUNTRY_DATABASE}.dbo.{COUNTRY_TABLE}"
TABLE_HC_SILVER = f"{SILVER_DATABASE}.{SILVER_SCHEMA}.hc_silver_historical"
TABLE_OKTA_SILVER = f"{SILVER_DATABASE}.{SILVER_SCHEMA}.okta_user_for_ai"
TABLE_CURSOR_SILVER = f"{SILVER_DATABASE}.{SILVER_SCHEMA}.cursor_usage"
TABLE_FACT_CURSOR_ACTIVE = f"{GOLD_DATABASE}.{GOLD_SCHEMA}.fact_cursor_active"
TABLE_FACT_CURSOR_ONBOARD = f"{GOLD_DATABASE}.{GOLD_SCHEMA}.fact_cursor_onboard"

NO_COUNTRY = "No Country"
HC_DIVISION_INC_DEFAULT = "Others"
CURSOR_ASSET_ID = "PENDING"
CURSOR_ASSET_NAME = "Cursor"
CURSOR_USE_CASE_CODE = "UC-9006-CURS-001"
CURSOR_USE_CASE_DISPLAY_NAME = "Active"
CURSOR_USE_CASE_MULTIPLIER = 1
CURSOR_AUTOMATION_POC = 1
CURSOR_TOTAL_HOURS_SAVED_POC = 0
FACT_CURSOR_ACTIVE_MERGE_KEY = "RecordSurrogateKey"
FACT_CURSOR_ONBOARD_MERGE_KEY = "OnboardSurrogateKey"

CURSOR_BRONZE_FILENAME = os.environ.get(
    "CURSOR_BRONZE_FILENAME", "team-usage-events-24970505-2026-09-25.csv"
)
ONELAKE_HOST = "onelake.dfs.fabric.microsoft.com"

# Default abfss paths (Fabric Copy ABFS path); no local_settings.py required.
ONELAKE_CURSOR_BRONZE_PATH = (
    f"abfss://{WORKSPACEID}@{ONELAKE_HOST}/"
    f"{LAKEHOUSE_AI_MEDALLION_ID}/Tables/Bronze/cursor_usage"
)

CONFIG_NAMES = [
    "WORKSPACEID",
    "LAKEHOUSE_AI_MEDALLION_ID",
    "LAKEHOUSE_AI_MEDALLION_BRONZE_ID",
    "LAKEHOUSE_AI_MEDALLION_SILVER_ID",
    "LAKEHOUSE_AI_MEDALLION_SILVER_DB_ID",
    "TABLE_HC_BRONZE",
    "TABLE_OKTA_BRONZE",
    "TABLE_CURSOR_BRONZE",
    "TABLE_COUNTRY",
    "TABLE_HC_SILVER",
    "TABLE_OKTA_SILVER",
    "TABLE_CURSOR_SILVER",
    "TABLE_FACT_CURSOR_ACTIVE",
    "TABLE_FACT_CURSOR_ONBOARD",
    "NO_COUNTRY",
    "HC_DIVISION_INC_DEFAULT",
    "CURSOR_ASSET_ID",
    "CURSOR_ASSET_NAME",
    "CURSOR_USE_CASE_CODE",
    "CURSOR_USE_CASE_DISPLAY_NAME",
    "CURSOR_USE_CASE_MULTIPLIER",
    "CURSOR_AUTOMATION_POC",
    "CURSOR_TOTAL_HOURS_SAVED_POC",
    "FACT_CURSOR_ACTIVE_MERGE_KEY",
    "FACT_CURSOR_ONBOARD_MERGE_KEY",
    "CURSOR_BRONZE_FILENAME",
    "ONELAKE_HOST",
    "ONELAKE_CURSOR_BRONZE_PATH",
]
